### ISSUE TITLE
server don't start

### ISSUE THREAD

**Issue by drom** [watson/airplanejs#2]
First of -- Awesome idea. I am dying to run.
I see server starting and closing very quickly.

Linux OpenSuSe Tumbleweed; node v9.2.0; NooElec dongle.

```
drom@drom:~/work/github/watson/airplanejs> node server.js 
Detached kernel driver
Found Rafael Micro R820T tuner
Exact sample rate is: 2000000.052982 Hz
Opening http://localhost:3000 in your favorite browser...
Closing down RTL-SDR device...
Reattached kernel driver
drom@drom:~/work/github/watson/airplanejs> 
```

**Comment by watson** [comment]
Weird. It thinks that you closed your browser right away and then thought you wanted to shut down. Detecting that was never 100% foolproof, so I think I'll just remove that code altogether. Thanks for reporting it 😃

**Comment by drom** [comment]
Commented out auto 'opn' now works!

<img width="415" alt="screenshot_20171211_003822" src="https://user-images.githubusercontent.com/511872/33822304-e942bc6c-de0b-11e7-9854-26fe53c440f3.png">

**Comment by watson** [comment]
Fixed and released in v1.1.5

**Comment by drom** [comment]
Yep. works! great super thanks!

**Comment by drom** [comment]
I would love doing more SDR using Node + Browser!
